### ISSUE TITLE
wrong number of parameters to hset

### ISSUE THREAD

**Issue by gflofst** [aspuru-guzik-group/funsies#4]
(base) PS C:\Users\gflofst> python hello-world.py
20210527 18:51:09.0| WARNING  | funsies._context:Fun:64 Opening new redis connection with default settings...
20210527 18:51:09.0| SUCCESS  | funsies._context:Fun:68 connected to localhost:6379
Traceback (most recent call last):
  File "hello-world.py", line 4, in <module>
    cmd = shell('sleep 2; echo 👋 🪐')
  File "C:\ProgramData\Anaconda3\lib\site-packages\funsies\ui.py", line 180, in shell
    operation = make_op(db, funsie, inputs, opt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\funsies\_graph.py", line 483, in make_op
    pipe.execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py", line 3961, in _execute_pipeline
    self.raise_first_error(commands, response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py", line 3968, in raise_first_error
    raise r
  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py", line 3956, in _execute_pipeline
    self.parse_response(connection, args[0], **options))
  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py", line 915, in parse_response
    response = connection.read_response()
  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (HSET funsies.funsies:8e2df32667aeed2c415a526e94cd6f38b7eff6ec hash 8e2df32667aeed2c415a526e94cd6f38b7eff6ec how 1 what sleep 2; echo 👋 🪐 error_tolerant 0) of pipeline caused  error: wrong number of arguments for 'hset' command

**Comment by gflofst** [comment]
[hello-world.txt](https://github.com/aspuru-guzik-group/funsies/files/6557506/hello-world.txt)
(the python file being used renamed from .py to attach here)

**Comment by clavigne** [comment]
Hi, thanks again for reviewing. I actually haven't tested the code on Windows, so I don't know how well it will work. I don't anticipate any issues... but they do sometimes crop up.

In this case, I believe the issue is that you are interfacing with a Redis instance of version < 4.0. The multiple argument hset (that use throughout) was introduced as part of Redis 4.0.0, according to https://redis.io/commands/hset 

This repository https://github.com/tporadowski/redis provides recent versions of Redis for windows. I'll update the README to include this information.

**Comment by gflofst** [comment]
ah, ok. I trust that this will work. Getting that working is going to unreasonably delay my review (and the last item). I'll let the other reviewers make sure that works.
